name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Example SAST equivalent using CodeQL (GitHub's security scanning tool)
      - name: Set up CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  execute:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Install dependencies and execute script
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat cat
          cat /etc/passwd
