name: Exploit Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  exploit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Compile Vulnerable Program
      run: |
        gcc -g -o vulnerable vulnerable.c
        chmod +x vulnerable

    - name: Run Exploit with GDB
      run: |
        ulimit -c unlimited
        python3 -c 'print("A" * 500)' > input.txt
        gdb -batch -ex "run $(< input.txt)" -ex "backtrace" -ex "info registers" -ex "x/40x \$rsp" ./vulnerable

    - name: Analyze Core Dump (if any)
      run: |
        if [ -f core ]; then
          gdb -c core -ex "bt" -ex "quit"
        else
          echo "No core dump found."
        fi
