name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sast:
    name: SAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # You would need to define your own SAST analysis steps here
      - name: Run SAST analysis
        run: |
          echo "Run SAST analysis steps here"
  
  execute_script:
    name: Execute Script
    runs-on: ubuntu-latest
    needs: sast # This ensures the `sast` job runs before `execute_script`
    container:
      image: node:14
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat

      - name: Run test script
        run: |
          node test.js
