name: Exploit Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gdb build-essential

    - name: Compile Vulnerable Program
      run: gcc -g -o vulnerable vulnerable.c

    - name: Run Exploit with GDB
      run: |
        python3 -c 'print("A" * 500)' > input.txt
        gdb -batch -ex "run $(< input.txt)" -ex "backtrace" -ex "info registers" -ex "x/40x \$rsp" ./vulnerable

    - name: Generate Exploit Pattern
      run: |
        echo "pattern" > pattern.txt
        ./msf-pattern_create -l 500 > pattern.txt
        cat pattern.txt

    - name: Analyze Core Dump (if any)
      if: failure()
      run: |
        gdb -c core -ex "bt" -ex "quit"

    - name: Archive Results
      uses: actions/upload-artifact@v2
      with:
        name: gdb-results
        path: .

