name: Test for Secrets and Container Breakout

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run environment variables test
      run: |
        echo "Listing all environment variables:"
        env

    - name: Check for secrets in files
      run: |
        echo "Checking for sensitive information in configuration files:"
        cat ~/.ssh/config || echo "No SSH config found"
        cat ~/.git-credentials || echo "No Git credentials found"
        cat ~/.npmrc || echo "No npm credentials found"

    - name: Attempt to access metadata service (if applicable)
      run: |
        echo "Trying to access metadata service:"
        curl http://169.254.169.254/latest/meta-data/ || echo "No metadata service accessible"
      
    - name: Explore file system
      run: |
        echo "Listing mounted filesystems:"
        df -h

    - name: Check for network access
      run: |
        echo "Testing network access:"
        ping -c 4 google.com || echo "No network access"
